"""
BDT Parser for Python Backend
==============================

This module parses BDT (Behandlungsdatentransfer) files generated by your Node.js EHR system
and prepares the data for AI summarization.

Add this to your backend.py or import it as a separate module.
"""

class BDTParser:
    """
    Parse BDT files to extract comprehensive patient data
    """
    
    def __init__(self):
        self.encoding = 'cp1252'  # German standard encoding
        
        # Field ID to name mapping
        self.field_map = {
            # Header
            '8000': 'bdt_version',
            '9206': 'software_id',
            '8316': 'record_type',
            '8100': 'patient_id',
            
            # Demographics
            '3100': 'last_name',
            '3101': 'first_name',
            '3110': 'date_of_birth',
            '3111': 'gender',
            '3102': 'address',
            '3103': 'city',
            '3106': 'state',
            '3107': 'country',
            '3112': 'phone',
            '3116': 'email',
            '3105': 'insurance',
            '3628': 'patient_number',
            '3629': 'blood_type',
            '3630': 'emergency_contact',
            
            # Allergies
            '8401': 'allergy_header',
            '8402': 'allergy_substance',
            '8403': 'allergy_severity',
            '8404': 'allergy_reaction',
            
            # Diagnoses
            '6200': 'diagnosis_header',
            '6201': 'icd_code',
            '6202': 'diagnosis_text',
            '6203': 'diagnosis_status',
            '6304': 'reason_for_visit',
            
            # Medications
            '6220': 'medication_header',
            '6221': 'medication_name',
            '6222': 'dosage_instructions',
            '6223': 'medication_start_date',
            '6225': 'medication_status',
            '6226': 'medication_indication',
            
            # Lab Results
            '8410': 'lab_header',
            '8411': 'lab_test_name',
            '8412': 'lab_result_value',
            '8413': 'lab_unit',
            '8418': 'lab_test_date',
            '8420': 'lab_status',
            '8421': 'lab_priority',
            '8422': 'lab_notes',
            
            # Procedures/Radiology
            '6330': 'procedure_header',
            '6331': 'procedure_date',
            '6333': 'procedure_name',
            '6334': 'procedure_notes',
            
            # Clinical Notes/Visits
            '6300': 'clinical_note_header',
            '6301': 'note_date',
            '6302': 'note_time',
            '6306': 'chief_complaint',
            '6304': 'reason_for_visit',  # Added reason for visit
            '6305': 'hpi',
            '6307': 'physical_exam',
            '6308': 'diagnosis_from_visit',
            '6309': 'treatment_plan',
            '6310': 'doctor_summary',
            
            # Vitals
            '3622': 'systolic_bp',
            '3623': 'diastolic_bp',
            '3624': 'heart_rate',
            '3625': 'temperature',
            '3626': 'weight',
            '3627': 'height',
        }
    
    def parse_bdt_line(self, line):
        """
        Parse a single BDT line
        
        Format: [3 digits: length][4 digits: field_id][content]
        Example: 0153100Allnigel
                 ^^^    ^^^^    ^^^^^^^^
                 len    id      content
        """
        line = line.strip('\r\n')
        
        if len(line) < 7:
            return None, None
        
        try:
            field_length = int(line[0:3])
            field_id = line[3:7]
            content = line[7:field_length] if field_length <= len(line) else line[7:]
            
            return field_id, content.strip()
        except (ValueError, IndexError):
            return None, None
    
    def parse_date(self, date_str):
        """Convert DDMMYYYY to YYYY-MM-DD"""
        if not date_str or len(date_str) != 8:
            return date_str
        
        try:
            day = date_str[0:2]
            month = date_str[2:4]
            year = date_str[4:8]
            return f"{year}-{month}-{day}"
        except:
            return date_str
    
    def parse_bdt_file(self, filepath):
        """
        Parse complete BDT file and return structured patient data
        
        Returns:
            dict: Structured patient data with all sections
        """
        patient_data = {
            'demographics': {},
            'allergies': [],
            'diagnoses': [],
            'medications': [],
            'lab_results': [],
            'procedures': [],
            'visits': [],
            'reason_for_visit': None,  # Global reason for visit
            'raw_data': {}
        }
        
        # Current item being built
        current_allergy = {}
        current_diagnosis = {}
        current_medication = {}
        current_lab = {}
        current_procedure = {}
        current_visit = {}
        current_vitals = {}
        
        try:
            encodings_to_try = [self.encoding, 'latin-1', 'utf-8']
            lines = None
            used_encoding = None

            for enc in encodings_to_try:
                try:
                    with open(filepath, 'r', encoding=enc) as f:
                        lines = f.readlines()
                    used_encoding = enc
                    if enc != self.encoding:
                        print(f"ℹ️ Decoded BDT using fallback encoding '{enc}'")
                    break
                except UnicodeDecodeError:
                    continue

            if lines is None:
                with open(filepath, 'r', encoding=self.encoding, errors='replace') as f:
                    lines = f.readlines()
                used_encoding = f"{self.encoding} (with replacement)"
                print("⚠️ Proceeding with lossy BDT decoding due to unsupported characters")
            
            for line in lines:
                field_id, content = self.parse_bdt_line(line)
                
                if not field_id or not content:
                    continue
                
                field_name = self.field_map.get(field_id, f'unknown_{field_id}')
                
                # Store raw data
                if field_name not in patient_data['raw_data']:
                    patient_data['raw_data'][field_name] = []
                patient_data['raw_data'][field_name].append(content)
                
                # === DEMOGRAPHICS ===
                if field_id in ['3100', '3101', '3110', '3111', '3102', '3112', '3116', '3105', '3628', '3629', '3630']:
                    if field_id == '3110':  # Date of birth
                        patient_data['demographics'][field_name] = self.parse_date(content)
                    else:
                        patient_data['demographics'][field_name] = content
                
                # === ALLERGIES ===
                elif field_id == '8401':  # Allergy header - save previous and start new
                    if current_allergy:
                        patient_data['allergies'].append(current_allergy.copy())
                    current_allergy = {}
                
                elif field_id == '8402':  # Allergy substance
                    current_allergy['substance'] = content
                
                elif field_id == '8403':  # Allergy severity
                    current_allergy['severity'] = content
                
                elif field_id == '8404':  # Allergy reaction
                    current_allergy['reaction'] = content
                
                # === DIAGNOSES ===
                elif field_id == '6200':  # Diagnosis header - save previous and start new
                    if current_diagnosis:
                        patient_data['diagnoses'].append(current_diagnosis.copy())
                    current_diagnosis = {}
                
                elif field_id == '6201':  # ICD code
                    current_diagnosis['icd_code'] = content
                
                elif field_id == '6202':  # Diagnosis text
                    current_diagnosis['diagnosis_text'] = content
                
                elif field_id == '6203':  # Diagnosis status
                    current_diagnosis['status'] = content
                
                # === MEDICATIONS ===
                elif field_id == '6220':  # Medication header - save previous and start new
                    if current_medication:
                        patient_data['medications'].append(current_medication.copy())
                    current_medication = {}
                
                elif field_id == '6221':  # Medication name
                    current_medication['name'] = content
                
                elif field_id == '6222':  # Dosage instructions
                    current_medication['dosage'] = content
                
                elif field_id == '6223':  # Start date
                    current_medication['start_date'] = self.parse_date(content)
                
                elif field_id == '6225':  # Status
                    current_medication['status'] = 'active' if content == 'A' else 'stopped'
                
                elif field_id == '6226':  # Indication
                    current_medication['indication'] = content
                
                # === LAB RESULTS ===
                elif field_id == '8410':  # Lab header - save previous and start new
                    if current_lab:
                        patient_data['lab_results'].append(current_lab.copy())
                    current_lab = {}
                
                elif field_id == '8411':  # Test name
                    current_lab['test_name'] = content
                
                elif field_id == '8412':  # Result value
                    current_lab['result_value'] = content
                
                elif field_id == '8413':  # Unit
                    current_lab['unit'] = content
                
                elif field_id == '8418':  # Test date
                    current_lab['test_date'] = self.parse_date(content)
                
                elif field_id == '8420':  # Status/Flag
                    current_lab['flag'] = content
                
                elif field_id == '8421':  # Priority
                    current_lab['priority'] = content
                
                elif field_id == '8422':  # Notes
                    current_lab['notes'] = content
                
                # === PROCEDURES ===
                elif field_id == '6330':  # Procedure header - save previous and start new
                    if current_procedure:
                        patient_data['procedures'].append(current_procedure.copy())
                    current_procedure = {}
                
                elif field_id == '6331':  # Procedure date
                    current_procedure['date'] = self.parse_date(content)
                
                elif field_id == '6333':  # Procedure name
                    current_procedure['name'] = content
                
                elif field_id == '6334':  # Procedure notes
                    current_procedure['notes'] = content
                
                # === CLINICAL NOTES / VISITS ===
                elif field_id == '6300':  # Visit header - save previous and start new
                    if current_visit:
                        # Add vitals to visit
                        if current_vitals:
                            current_visit['vitals'] = current_vitals.copy()
                        patient_data['visits'].append(current_visit.copy())
                    current_visit = {}
                    current_vitals = {}
                
                elif field_id == '6301':  # Visit date
                    current_visit['date'] = self.parse_date(content)
                
                elif field_id == '6302':  # Visit time
                    current_visit['time'] = content
                
                elif field_id == '6306':  # Chief complaint
                    current_visit['chief_complaint'] = content
                
                elif field_id == '6304':  # Reason for visit
                    current_visit['reason_for_visit'] = content
                    # Also store as global reason for visit (latest one)
                    patient_data['reason_for_visit'] = content
                
                elif field_id == '6305':  # HPI
                    current_visit['hpi'] = content
                
                elif field_id == '6307':  # Physical exam
                    current_visit['physical_exam'] = content
                
                elif field_id == '6308':  # Diagnosis
                    current_visit['diagnosis'] = content
                
                elif field_id == '6309':  # Treatment plan
                    current_visit['treatment_plan'] = content
                
                elif field_id == '6310':  # Doctor summary
                    current_visit['doctor_summary'] = content
                
                # === VITALS (part of visits) ===
                elif field_id == '3622':  # Systolic BP
                    current_vitals['systolic'] = content
                
                elif field_id == '3623':  # Diastolic BP
                    current_vitals['diastolic'] = content
                
                elif field_id == '3624':  # Heart rate
                    current_vitals['heart_rate'] = content
                
                elif field_id == '3625':  # Temperature
                    current_vitals['temperature'] = content
                
                elif field_id == '3626':  # Weight
                    current_vitals['weight'] = content
                
                elif field_id == '3627':  # Height
                    current_vitals['height'] = content
            
            # Save last items
            if current_allergy:
                patient_data['allergies'].append(current_allergy)
            if current_diagnosis:
                patient_data['diagnoses'].append(current_diagnosis)
            if current_medication:
                patient_data['medications'].append(current_medication)
            if current_lab:
                patient_data['lab_results'].append(current_lab)
            if current_procedure:
                patient_data['procedures'].append(current_procedure)
            if current_visit:
                if current_vitals:
                    current_visit['vitals'] = current_vitals
                patient_data['visits'].append(current_visit)
            
            return patient_data
            
        except Exception as e:
            print(f"❌ Error parsing BDT file: {e}")
            return None
    
    def format_for_ai(self, patient_data):
        """
        Format parsed BDT data into readable text for AI processing
        
        This matches the format your AI expects
        """
        if not patient_data:
            return ""
        
        lines = []
        
        # === DEMOGRAPHICS ===
        demo = patient_data.get('demographics', {})
        
        lines.append("=" * 60)
        lines.append("PATIENT INFORMATION")
        lines.append("=" * 60)
        
        name = f"{demo.get('first_name', '')} {demo.get('last_name', '')}"
        lines.append(f"Name: {name.strip()}")
        lines.append(f"Date of Birth: {demo.get('date_of_birth', 'Unknown')}")
        lines.append(f"Gender: {demo.get('gender', 'Unknown')}")
        lines.append(f"Patient ID: {demo.get('patient_id', demo.get('patient_number', 'Unknown'))}")
        
        if demo.get('blood_type'):
            lines.append(f"Blood Type: {demo.get('blood_type')}")
        if demo.get('phone'):
            lines.append(f"Phone: {demo.get('phone')}")
        if demo.get('email'):
            lines.append(f"Email: {demo.get('email')}")
        if demo.get('insurance'):
            lines.append(f"Insurance: {demo.get('insurance')}")
        
        lines.append("")
        
        # === ALLERGIES ===
        allergies = patient_data.get('allergies', [])
        if allergies:
            lines.append("ALLERGIES:")
            for allergy in allergies:
                substance = allergy.get('substance', 'Unknown')
                severity = allergy.get('severity', '')
                reaction = allergy.get('reaction', '')
                
                allergy_text = f"  • {substance}"
                if severity:
                    allergy_text += f" (Severity: {severity})"
                if reaction:
                    allergy_text += f" - Reaction: {reaction}"
                
                lines.append(allergy_text)
            lines.append("")
        
        # === DIAGNOSES ===
        diagnoses = patient_data.get('diagnoses', [])
        if diagnoses:
            lines.append("ACTIVE DIAGNOSES:")
            for dx in diagnoses:
                icd = dx.get('icd_code', '')
                text = dx.get('diagnosis_text', '')
                status = dx.get('status', '')
                
                dx_line = f"  • {icd}: {text}" if icd else f"  • {text}"
                if status == 'G':
                    dx_line += " [Confirmed]"
                elif status == 'V':
                    dx_line += " [Suspected]"
                
                lines.append(dx_line)
            lines.append("")
        
        # === MEDICATIONS ===
        medications = patient_data.get('medications', [])
        if medications:
            lines.append("CURRENT MEDICATIONS:")
            for med in medications:
                name = med.get('name', 'Unknown')
                dosage = med.get('dosage', '')
                status = med.get('status', 'active')
                indication = med.get('indication', '')
                
                med_line = f"  • {name}"
                if dosage:
                    med_line += f" - {dosage}"
                if status == 'stopped':
                    med_line += " [STOPPED]"
                if indication:
                    med_line += f" (For: {indication})"
                
                lines.append(med_line)
            lines.append("")
        
        # === LAB RESULTS ===
        labs = patient_data.get('lab_results', [])
        if labs:
            lines.append("RECENT LAB RESULTS:")
            for lab in labs:
                test_name = lab.get('test_name', 'Unknown')
                value = lab.get('result_value', 'Pending')
                unit = lab.get('unit', '')
                date = lab.get('test_date', '')
                flag = lab.get('flag', '')
                
                lab_line = f"  • {test_name}: {value}"
                if unit:
                    lab_line += f" {unit}"
                if date:
                    lab_line += f" (Date: {date})"
                if flag in ['H', 'HH']:
                    lab_line += " [HIGH]"
                elif flag in ['L', 'LL']:
                    lab_line += " [LOW]"
                
                lines.append(lab_line)
            lines.append("")
        
        # === PROCEDURES ===
        procedures = patient_data.get('procedures', [])
        if procedures:
            lines.append("PROCEDURES/IMAGING:")
            for proc in procedures:
                name = proc.get('name', 'Unknown')
                date = proc.get('date', '')
                notes = proc.get('notes', '')
                
                proc_line = f"  • {name}"
                if date:
                    proc_line += f" (Date: {date})"
                if notes:
                    proc_line += f"\n    Notes: {notes}"
                
                lines.append(proc_line)
            lines.append("")
        
        # === VISIT HISTORY ===
        visits = patient_data.get('visits', [])
        if visits:
            lines.append("RECENT VISIT HISTORY:")
            for idx, visit in enumerate(visits[:5], 1):  # Last 5 visits
                lines.append(f"\n  Visit #{idx}:")
                
                if visit.get('date'):
                    lines.append(f"  Date: {visit['date']}")
                
                if visit.get('chief_complaint'):
                    lines.append(f"  Chief Complaint: {visit['chief_complaint']}")
                
                # Vitals
                vitals = visit.get('vitals', {})
                if vitals:
                    vital_parts = []
                    if vitals.get('systolic') and vitals.get('diastolic'):
                        vital_parts.append(f"BP: {vitals['systolic']}/{vitals['diastolic']}")
                    if vitals.get('heart_rate'):
                        vital_parts.append(f"HR: {vitals['heart_rate']}")
                    if vitals.get('temperature'):
                        vital_parts.append(f"Temp: {vitals['temperature']}°C")
                    if vitals.get('weight'):
                        vital_parts.append(f"Weight: {vitals['weight']}kg")
                    
                    if vital_parts:
                        lines.append(f"  Vitals: {', '.join(vital_parts)}")
                
                if visit.get('diagnosis'):
                    lines.append(f"  Diagnosis: {visit['diagnosis']}")
                
                if visit.get('treatment_plan'):
                    lines.append(f"  Plan: {visit['treatment_plan']}")
                
                if visit.get('doctor_summary'):
                    lines.append(f"  Summary: {visit['doctor_summary']}")
            
            lines.append("")
        
        lines.append("=" * 60)
        lines.append("END OF PATIENT RECORD")
        lines.append("=" * 60)
        
        return '\n'.join(lines)


# Example usage in your backend.py:
"""
# In your GDTHandler class, update the on_modified method:

def on_modified(self, event):
    if event.src_path == FULL_PATH:
        print(f"📂 File detected: {event.src_path}")
        
        try:
            # Check if this is a BDT file reference
            with open(FULL_PATH, 'r', encoding='latin-1') as f:
                content = f.read()
                
            # Look for BDT file reference
            if 'BDT_FILE:' in content:
                # Extract BDT filename
                for line in content.split('\n'):
                    if 'BDT_FILE:' in line:
                        bdt_filename = line.split('BDT_FILE:')[1].strip()
                        bdt_path = os.path.join(WATCH_FOLDER, bdt_filename)
                        
                        # Parse BDT file
                        parser = BDTParser()
                        patient_data = parser.parse_bdt_file(bdt_path)
                        
                        if patient_data:
                            # Format for AI
                            formatted_text = parser.format_for_ai(patient_data)
                            
                            # Send to AI
                            ai_summary = generate_ai_summary_from_text(formatted_text)
                            
                            # Cache and use summary
                            # ... your existing code
                        break
            else:
                # Fall back to old GDT parsing
                # ... your existing GDT code
                
        except Exception as e:
            print(f"❌ ERROR: {e}")
"""
