FROM node:18-slim
WORKDIR /app
COPY package*.json ./
COPY server/package*.json ./server/
COPY scripts/ ./scripts/
RUN npm install
COPY . .
RUN mkdir -p /app/ehr_exchange
EXPOSE 5000
WORKDIR /app/server
CMD ["node", "server.js"]